### ISSUE TITLE
DATE column type is Character.

### ISSUE THREAD

**Issue by barnettjacob** [rstats-db/odbc#11]
### Issue Description and Expected Result
While datetimes seem to load nicely as dttm type columns, dates are currently parsed as character type - would be great to iron out this tiny kink. Let me know if I can provide any more info. Thanks.

### Database
SQL Server 2014 (12.0.5000.0)

### Reproducible Example
Example:
```r
library(odbc)
con <- dbConnect(odbc::odbc(), "Warehouse")
tbl_df(dbGetQuery(con, 'select top 10 Interestdate, InterestDateTime FROM vwInterestFlow'))
```

```
   Interestdate    InterestDateTime
          <chr>              <dttm>
1    2013-04-23 2013-04-23 19:41:32
2    2013-04-23 2013-04-24 00:12:33
3    2013-04-23 2013-04-24 00:59:41
4    2013-04-23 2013-04-23 06:54:34
5    2013-04-23 2013-04-23 05:48:09
6    2013-04-23 2013-04-23 20:17:58
7    2013-04-23 2013-04-23 16:25:53
8    2013-04-23 2013-04-23 13:39:59
9    2013-04-23 2013-04-24 00:26:43
10   2013-04-23 2013-04-23 01:38:07
```

![image](https://cloud.githubusercontent.com/assets/7270997/20172971/2dd9530a-a72f-11e6-893c-b38964015c11.png)

<details>
<summary>Session info</summary>
```
### Session Info
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  English_United States.1252  
 tz       Europe/London               
 date     2016-11-10                  

### Packages
 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                         
 assertthat   0.1        2013-12-06 CRAN (R 3.3.1)                 
 curl         1.2        2016-08-13 CRAN (R 3.3.1)                 
 DBI          0.5-12     2016-11-09 Github (rstats-db/DBI@4f00863) 
 devtools     1.12.0     2016-06-24 CRAN (R 3.3.1)                 
 digest       0.6.10     2016-08-02 CRAN (R 3.3.1)                 
 dplyr      * 0.5.0      2016-06-24 CRAN (R 3.3.1)                 
 git2r        0.15.0     2016-05-11 CRAN (R 3.3.1)                 
 httr         1.2.1      2016-07-03 CRAN (R 3.3.1)                 
 knitr        1.14       2016-08-13 CRAN (R 3.3.1)                 
 lazyeval     0.2.0      2016-06-12 CRAN (R 3.3.1)                 
 magrittr     1.5        2014-11-22 CRAN (R 3.3.1)                 
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.1)                 
 odbc       * 0.0.0.9000 2016-11-09 Github (rstats-db/odbc@7eef2f3)
 R6           2.1.3      2016-08-19 CRAN (R 3.3.1)                 
 Rcpp         0.12.7     2016-09-05 CRAN (R 3.3.1)                 
 tibble       1.2        2016-08-26 CRAN (R 3.3.1)                 
 withr        1.0.2      2016-06-20 CRAN (R 3.3.1)
```

**Comment by jimhester** [comment]
Can you send the results of 

```r
dbGetQuery(con, "SELECT * from INFORMATION_SCHEMA.COLUMNS where table_name = 'vwInterestFlow' AND COLUMN_NAME IN ('Interestdate', 'Interestdatetime')")
```

Also the result of the following would be useful.
```
q <- dbSendQuery(con, 'select top 10 Interestdate, InterestDateTime FROM vwInterestFlow'))
dbColumnInfo(q)
```

I simple example returns as Date object as expected for me, so something must be different with your server setup.
``` r
(con <- dbConnect(odbc::odbc(), "test"))
#> <OdbcConnection> dbo@WINDEV1609SYS\SQLEXPRESS
#>   Database: master
#>   Microsoft SQL Server Version: 13.00.1601
str(dbGetQuery(con, "SELECT cast ('1992-02-27' as date) as a"))
#> 'data.frame':    1 obs. of  1 variable:
#>  $ a: Date, format: "1992-02-27"
```

**Comment by barnettjacob** [comment]
`dbGetQuery(con, "SELECT * from INFORMATION_SCHEMA.COLUMNS where table_name = 'vwInterestFlow' AND COLUMN_NAME IN ('Interestdate', 'Interestdatetime')")`

![image](https://cloud.githubusercontent.com/assets/7270997/20180046/a166e0dc-a750-11e6-86ce-226016534123.png)

```
q <- dbSendQuery(con, 'select top 10 Interestdate, InterestDateTime FROM vwInterestFlow'))
dbColumnInfo(q)
```

![image](https://cloud.githubusercontent.com/assets/7270997/20179999/7b5d0538-a750-11e6-8ae0-ab01eb91ad3f.png)

**Comment by jimhester** [comment]
The `type -9` is the issue, but I don't know why that type is being used, the date types defined in the headers are [SQL_DATE (9)](https://github.com/Microsoft/ODBC-Specification/blob/8fe461b6886bba1fd6d8170f2ddc50fa903ce742/Windows/inc/sqlext.h#L464) and [SQL_TYPE_DATE (91)](https://github.com/Microsoft/ODBC-Specification/blob/8fe461b6886bba1fd6d8170f2ddc50fa903ce742/Windows/inc/sql.h#L223)

what do you get from the following? You can see for my server it returns `SQL_TYPE_DATE (91)`.
``` r
(con <- dbConnect(odbc::odbc(), "test"))
#> <OdbcConnection> dbo@WINDEV1609SYS\SQLEXPRESS
#>   Database: master
#>   Microsoft SQL Server Version: 13.00.1601
q <- dbSendQuery(con, "SELECT cast ('1992-02-27' as date) as a")
dbColumnInfo(q)
#>   name type
#> 1    a   91
```

**Comment by jimhester** [comment]
Just a small update `-9` seems to be NVARCHAR, I don't know why native date columns would be reported as that but I am not sure there is much this package can do about it if that is what the driver is reporting. Could you try casting the column explicitly to date?

```r
str(dbGetQuery(con, 'select top 10 cast(Interestdate as date), InterestDateTime FROM vwInterestFlow'))
```

**Comment by barnettjacob** [comment]
For `(con <- dbConnect(odbc::odbc(), "Warehouse"))`, I get:
![image](https://cloud.githubusercontent.com/assets/7270997/20195576/0bf846c8-a78f-11e6-9437-511965ed9b08.png)

For `q <- dbSendQuery(con, "SELECT cast ('1992-02-27' as date) as a")`, I get:
![image](https://cloud.githubusercontent.com/assets/7270997/20195632/402a5242-a78f-11e6-8c91-8bd3baa59971.png)

And for `str(dbGetQuery(con, 'select top 10 cast(Interestdate as date), InterestDateTime FROM vwInterestFlow'))`
![image](https://cloud.githubusercontent.com/assets/7270997/20195701/80a687aa-a78f-11e6-8aec-90be1eae3886.png)

I'll ask one of our db guys about the -9!
Cheers
Jacob

**Comment by barnettjacob** [comment]
Hey Jim, I didn't ever manage to get to the bottom of this but the -9 has now become a 91 on our database?!?!? Closing the issue, thanks for looking.
Jacob

**Comment by jimhester** [comment]
Ok great, sorry about the original issue but I am glad it is resolved!

**Comment by tseaward** [comment]
Hi, I'm currently experiencing this issue - where the date column type returned is -9. @barnettjacob  do you have any idea how you resolved this?

**Comment by gacolitti** [comment]
I'm still having this issue. Columns stored as date on SQL server are parsed as character type. 

``` r
library(odbc)
#> Warning: package 'odbc' was built under R version 3.6.3
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.6.3
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
con <- dbConnect(odbc::odbc(), "udt")
tbl_df(dbGetQuery(con, 'select top 5 wet_date FROM farminganalytics.field_lot_detail'))
#> # A tibble: 5 x 1
#>   wet_date  
#>   <chr>     
#> 1 2016-09-18
#> 2 2016-09-17
#> 3 2016-09-13
#> 4 2016-09-20
#> 5 2016-09-18
```

<sup>Created on 2020-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by shrektan** [comment]
I’m not sure the root cause but changing the odbc driver will help. I mean, the default driver on Windows has such issue. Replacing it fixes this on my machine.

**Comment by gacolitti** [comment]
I believe I have the latest ODBC driver for SQL Server (2017.175.02.01). I still haven't figured out what is causing this issue.

**Comment by gacolitti** [comment]
It turns out I wasn't actually using the driver I thought I was. So others that find themselves here might want to double check that they are passing the proper driver to ```dbConnect```. 

This works:

````
con <-
  dbConnect(
    odbc(),
    driver = "ODBC Driver 17 for SQL Server", 
    server = "server",
    database = "database",
    username = "username",
    password = "password",
    trusted_connection = "yes" # for windows authentication
  )
